title: '"The World is Our Classroom"'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8608124
color:
  saturation: 1
  brandStrength: 0.1712593059055507
  lightness: 0.8990442
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.8811231
layout_spectrum: 0.5274791
name: Students Teach Students Leadership Institute
